### ISSUE TITLE
Fibonacci app, Chapter04 - ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by maus2maus** [PacktPublishing/Node.js-14-Web-Development#9]
When I run Fibonacci app, Chapter04 on Windows 10, Chrome and press Submit button I get - ECONNREFUSED 127.0.0.1:80
Antivirus is turned off, firewall is turned off.
Could you help me to fix it?

**Comment by robogeek** [comment]
The connection is refused against port 80 - that's what the URL says.

In bin/www there is a script for running the server, and the default is to
use port 3000.  That means you should use 127.0.0.1:3000 as the connection
URL, instead.

**Comment by maus2maus** [comment]
Ok, I will explain my steps.
1) I do - npm start, no errors yet
2) I go to http://localhost:3000/fibonacci -- I can see the page with the form, no errors
3) I Submit a value through the form, and the address changes to -- http://localhost:3000/fibonacci?fibonum=2 . I check in the network tab where the request went -- http://localhost:3000/fibonacci?fibonum=2 . This seems correct too, but I get status code 500 and the message on the page is: ECONNREFUSED 127.0.0.1:80

So at first port 3000 was working okey for me, but when submit happened - port 80 somehow comes into play

**Comment by robogeek** [comment]
Which implementation is the code configured for?  For example, fibonacci-rest does REST calls in the background.  In that case the SERVERPORT environment variable controls the port it connects to the fiboserver process.

**Comment by maus2maus** [comment]
Oh, right it was configured for  fibonacci-rest. Closing this one

**Comment by robogeek** [comment]
Glad to be of educational service.
